src/Form/SortieType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use App\Entity\Lieu;
use App\Entity\Sortie;
use App\Entity\Ville;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SortieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom',TextType::class,[
                'label'=> 'Nom de la sortie  '
            ])
            ->add('campus', EntityType::class, [
                'label'=> 'campus  ',
                'class' => Campus::class,
                'choice_label' => 'nom'
            ])
            ->add('ville', EntityType::class,[
            'label' => 'Ville ',
            'class' => Ville::class,
            'choice_label' => 'nom',
                'attr' => [
                    'id' => 'sortie_ville',

    ]
            ])
            ->add('lieu', EntityType::class,[
                'label' => 'Lieu  ',
                'class' => Lieu::class,
                'attr' => [
                    'id' => 'sortie_lieu'],
                'choice_label' => 'nom'

            ])
            ->add('dateHeureDebut',DateTimeType::class,[
                'label' => 'Dâte et heure de la sortie  ',
                'date_widget'=> 'single_text',
                'time_widget'=> 'single_text',
                'html5' => true
            ])
            ->add('duree', NumberType::class,[
                'label'=> 'Durée de la sortie : (en minutes)'
            ])
            ->add('dateLimiteInscription', DateTimeType::class,[
                'label' => 'Dâte limite d\'inscription  ',
                'date_widget'=> 'single_text',
                'time_widget'=> 'single_text',
                'html5' => true
            ])
            ->add('nbInscriptionMax', NumberType::class,[
                'label' => 'Nombre de places  '
            ])
            ->add('infosSortie', TextareaType::class,[
                'label'=> 'Descriptions et infos  '
            ]);
    }
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sortie::class,
        ]);
    }
}

src/Form/modele/ModeleFiltres.php
<?php

namespace App\Form\modele;

use App\Entity\Campus;

class ModeleFiltres
{

    private ?Campus $campus = null;
    private  ?string $nom = null;
    private ?bool $sortieOrganisateur = null;
    private ?bool $sortieInscrit = null;
    private ?bool $sortiePasInscrit = null;
    private ?bool $sortiePasses = null;

    private ?\DateTime $DateSortie = null;
    private ?\DateTime $DateCloture = null;

    public function __construct()
{
}

    /**
     * @return Campus|null
     */
    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    /**
     * @param Campus|null $campus
     */
    public function setCampus(?Campus $campus): void
    {
        $this->campus = $campus;
    }

    /**
     * @return string|null
     */
    public function getNom(): ?string
    {
        return $this->nom;
    }

    /**
     * @param string|null $nom
     */
    public function setNom(?string $nom): void
    {
        $this->nom = $nom;
    }

    /**
     * @return bool|null
     */
    public function getSortieOrganisateur(): ?bool
    {
        return $this->sortieOrganisateur;
    }

    /**
     * @param bool|null $sortieOrganisateur
     */
    public function setSortieOrganisateur(?bool $sortieOrganisateur): void
    {
        $this->sortieOrganisateur = $sortieOrganisateur;
    }

    /**
     * @return bool|null
     */
    public function getSortieInscrit(): ?bool
    {
        return $this->sortieInscrit;
    }

    /**
     * @param bool|null $sortieInscrit
     */
    public function setSortieInscrit(?bool $sortieInscrit): void
    {
        $this->sortieInscrit = $sortieInscrit;
    }

    /**
     * @return bool|null
     */
    public function getSortiePasInscrit(): ?bool
    {
        return $this->sortiePasInscrit;
    }

    /**
     * @param bool|null $sortiePasInscrit
     */
    public function setSortiePasInscrit(?bool $sortiePasInscrit): void
    {
        $this->sortiePasInscrit = $sortiePasInscrit;
    }

    /**
     * @return bool|null
     */
    public function getSortiePasses(): ?bool
    {
        return $this->sortiePasses;
    }

    /**
     * @param bool|null $sortiePasses
     */
    public function setSortiePasses(?bool $sortiePasses): void
    {
        $this->sortiePasses = $sortiePasses;
    }

    /**
     * @return \DateTime|null
     */
    public function getDateSortie(): ?\DateTime
    {
        return $this->DateSortie;
    }

    /**
     * @param \DateTime|null $DateSortie
     */
    public function setDateSortie(?\DateTime $DateSortie): void
    {
        $this->DateSortie = $DateSortie;
    }


    /**
     * @return \DateTime|null
     */
    public function getDateCloture(): ?\DateTime
    {
        return $this->DateCloture;
    }

    /**
     * @param \DateTime|null $DateCloture
     */
    public function setDateCloture(?\DateTime $DateCloture): void
    {
        $this->DateCloture = $DateCloture;
    }




}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\modele\ModeleFiltres;
use App\Repository\EtatRepository;
use App\Entity\Etat;
use App\Entity\Sortie;
use App\Form\FiltreType;
use App\Form\SortieType;
use App\Repository\LieuRepository;
use App\Repository\SortieRepository;
use App\Utils\Uploader;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;


#[Route('/sortie', name: 'sortie_')]
class SortieController extends AbstractController
{
    private $entityManager;
    private $etatRepository;

    public function __construct(EntityManagerInterface $entityManager, EtatRepository $etatRepository)
    {
        $this->entityManager = $entityManager;
        $this->etatRepository = $etatRepository;
    }

    #[Route('/list', name: 'list')]
    public function profile(EntityManagerInterface $entityManager, EtatRepository $etatRepository, Uploader $etatSorties, SortieRepository $sortieRepository, Request $request): Response
    {


        // Debut des filtes

        $filtres = new ModeleFiltres();
        $filtreForm = $this->createForm(FiltreType::class, $filtres);
        $filtreForm->handleRequest($request);
        if ($filtreForm->isSubmitted() && $filtreForm->isValid()) {
            $sortieFiltre = $sortieRepository->findFiltered($filtres);
        } else {
            $etatSorties->majEtat($etatRepository, $sortieRepository, $filtres, $this->getUser(), $entityManager);
            $sortieFiltre = $sortieRepository->findFiltered($filtres);
        }




//        dd($sortieFiltre);
        //$sortie = $sortieRepository->findAll();
        return $this->render('sortie/list.html.twig', [
            'sortieFiltre'=>$sortieFiltre, 'filtre' => $filtreForm->createView(),

        ]);
    }


    #[Route('/new', name: 'new')]
    public function new(Request $request, SortieRepository $sortieRepository, UserInterface $user): Response
    {
        $etatRepository = $this->entityManager->getRepository(Etat::class);

        $sortie = new Sortie();

        $sortieForm = $this->createForm(SortieType::class, $sortie);
        $sortieForm->handleRequest($request);

        if ($sortieForm->isSubmitted() && $sortieForm->isValid()) {

            $etatCree = $etatRepository->findOneBy(['libelle' => 'Créée']);
            if (!$etatCree) {
                $etatCree = new Etat();
                $etatCree->setLibelle('Créée');
                $this->entityManager->persist($etatCree);
            }
            $sortie->setEtat($etatCree);

            $sortie->setUser($user); // set the connected user as the organizer

            $sortieRepository->save($sortie, true);

            $this->addFlash('success', 'Sortie créée avec succès !');

            return $this->redirectToRoute('sortie_details', ['id' => $sortie->getId()]);
        }

        return $this->render('sortie/new.html.twig', [
            'sortie' => $sortie,
            'sortieForm' => $sortieForm->createView()
        ]);
    }
    #[Route('/lieu_by_ville', name: 'lieux_by_ville', methods: ['GET', 'POST'])]
    public function getLieuxByVille(Request $request, LieuRepository $lieuRepository)
    {
        $villeId = $request->request->get('ville_id');

        $lieux = $lieuRepository->findBy(['ville' => $villeId]);

        $lieuxArray = array();
        foreach ($lieux as $lieu) {
            $lieuData = array(
                'id' => $lieu->getId(),
                'nom' => $lieu->getNom()
            );
            array_push($lieuxArray, $lieuData);
        }

        $response = new JsonResponse();
        $response->setData($lieuxArray);

        return $response;
    }



    #[Route('/{id}', name: 'details')]
    public function show(int $id, SortieRepository $sortieRepository): Response
    {
        //récupération d'une série par son id
        $sortie = $sortieRepository->find($id);

        if (!$sortie) {
            //lance une erreur 404 si la série n'existe pas
            throw $this->createNotFoundException("Oops ! Serie not found !");
        }

        return $this->render('sortie/details.html.twig', [
            'sortie' => $sortie
        ]);
    }




    #[Route('edit/{id}', name: 'edit')]
    public function edit(Request $request, int $id, SortieRepository $sortieRepository): Response
    {
        $sortie = $sortieRepository->find($id);

        $form = $this->createForm(SortieType::class, $sortie);
        $form->handleRequest($request);
        if ($sortie->getEtat()->getLibelle()=== "Annulée"){
            $this->addFlash('error', "Impossible modifiée une sortie déjà Annulée");
            return $this->redirectToRoute('sortie_list');
        }
        if ($form->isSubmitted() && $form->isValid()) {

            $sortieRepository->save($sortie, true);
            $this->addFlash('success', 'Sortie modifiée avec succès.');

            return $this->redirectToRoute('sortie_details', ['id' => $sortie->getId()]);
        }

        return $this->render('sortie/edit.html.twig', [
            'sortie' => $sortie,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/publier/{id}', name: 'publier')]
    public function Publier(int $id, SortieRepository $sortieRepository, EtatRepository $etatRepository)
    {
        $sortie = $sortieRepository->find($id);

        $etat = $etatRepository->findOneBy(['libelle' => 'Ouverte']);

        $sortie->setEtat($etat);

        $sortieRepository->save($sortie, true);

        $this->addFlash('success', 'Sortie publiées avec succès.');
        return $this->redirectToRoute('sortie_list');
    }

    #[Route('/inscription/{id}', name: 'inscription')]
    public function inscriptionSortie(int $id, SortieRepository $sortieRepository): Response
    {


        // Récupération de la sortie
        $sortie = $sortieRepository->find($id);

        // Vérification si la sortie est complète
        if ($sortie->getUsers()->count() >= $sortie->getNbInscriptionMax()) {
            $this->addFlash('error', 'La sortie est complète.');
            return $this->redirectToRoute('sortie_list');
        }
        if (!($sortie->getEtat()->getLibelle() == "Ouverte")) {
            $this->addFlash('error', "L'inscription n'est pas possible.");
            return $this->redirectToRoute('sortie_list');
        }

        // Vérification si l'utilisateur est déjà inscrit
        $user = $this->getUser();
        if ($sortie->getUsers()->contains($user)) {
            $this->addFlash('error', 'Vous êtes déjà inscrit à cette sortie.');
            return $this->redirectToRoute('sortie_list');
        }

        // Inscription de l'utilisateur
        $sortie->addUser($user);

        $sortieRepository->save($sortie, true);

        // Retour de la réponse/la route
        $this->addFlash('success', 'Vous etes bien inscrit a cette sortie.');
        return $this->redirectToRoute('sortie_details', ['id' => $sortie->getId()]);
    }

    #[Route('/desinscription/{id}', name: 'desinscription')]
    public function desinscriptionSortie(int $id, SortieRepository $sortieRepository): Response
    {
        // Récupération de la sortie
        $sortie = $sortieRepository->find($id); // Récupération de l'utilisateur

        $user = $this->getUser(); // Désinscription de l'utilisateur
        $sortie->removeUser($user);
        $sortieRepository->save($sortie, true); // Retour de la réponse

    return $this->redirectToRoute('sortie_list');
    }


    #[Route('cancel/{id}', name: 'cancel')]
    public function annulerSortie(int $id,
                                  Request $request,
                                  SortieRepository $sortieRepository,
                                  EntityManagerInterface $entityManager,
                                  UserInterface $user): Response
    {
        $sortie = $sortieRepository->find($id);

        // Vérifier que l'utilisateur est bien l'organisateur de la sortie
        if ($sortie->getUser() !== $user) {
            throw new AccessDeniedHttpException("Vous n'êtes pas autorisé à annuler cette sortie");
        }

        // Vérifier que la sortie n'a pas encore commencé
        $dateHeureDebut = $sortie->getDateHeureDebut();
        $dateAuj = new \DateTime();
        if ($dateAuj >= $dateHeureDebut) {
            throw new \Exception("Impossible d'annuler une sortie déjà commencée");
        }
        if ($sortie->getEtat()->getLibelle()=== "Annulée"){
            throw new \Exception("Impossible d'annuler une sortie déjà Annulée");
        }

        //création du formulaire d'ajout de motif d'annulation + boutton annuler
        $form = $this->createFormBuilder()
            ->add('motif', TextareaType::class, [
                'label' => "Motif d'annulation",
                'attr' => [
                    'placeholder' => "Indiquez le motif d'annulation de la sortie",
                    'rows' => 4,
                ],
            ])
            ->add('annuler', SubmitType::class, [
                'label' => "Annuler la sortie",
                'attr' => [
                    'class' => 'btn btn-danger',
                ],
            ])
            ->getForm();

        $form->handleRequest($request);

        //récupération données du formaulaire
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            // Mettre à jour la sortie et la sauvegarder
            $sortie->setEtat($this->etatRepository->findOneByLibelle('Annulée'));

templates/sortie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/sortie/annuler.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annuler une sortie{% endblock %}
{% block header %}
    <link rel="stylesheet" href="{{ asset('assets/css/containerPrinc.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/navBis.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/annuler.css') }}">
{% endblock %}

{% block body %}
    <div class="containerPrinc">
        <div class="ez flexerMID">
    <fieldset class="fieldset1">
    <legend>Annuler la sortie "{{ sortie.nom }}"</legend>
    {% if sortie.dateHeureDebut >= "now"|date %}
        {{ form_start(form) }}
        {{ form_row(form.motif) }}
        {{ form_row(form.annuler) }}
        {{ form_end(form) }}
    {% else %}
        <p>Impossible d'annuler une sortie déjà commencée</p>
    {% endif %}
</fieldset>
    </div>
</div>
{% endblock %}

templates/sortie/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }} | Détails de la sortie
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{{ asset('assets/css/containerPrinc.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/styleSortieDetails.css') }}">
{% endblock %}



{% block body %}

    <div class="containerPrinc">
        <div class="ez flexerMID">
            <fieldset class="fieldset1">
                <legend>Détails de la sortie</legend>
                    <p>Nom de la sortie : {{ sortie.nom }}</p>
                    <p class="margT">Date et heure de la sortie : {{ sortie.dateHeureDebut | date('Y-m-d') }}</p>
                    <p class="margT">Date limite d'inscription : {{ sortie.dateLimiteInscription | date('Y-m-d') }}</p>
                    <p class="margT">Nombre de places : {{ sortie.nbInscriptionMax }}</p>
                    <p class="margT">Durée : {{ sortie.duree }} minutes</p>
                    <p class="margT">Description et infos : {{ sortie.infosSortie }}</p>


                    <p class="margT">Campus : {{ sortie.campus.nom }}</p>
                    <p class="margT">Lieu: {{ sortie.lieu.nom }} , {{ sortie.lieu.ville.nom }}</p>
                    <p class="margT">Rue : {{ sortie.lieu.rue }}</p>
                    <p class="margT">Code postal : {{ sortie.lieu.ville.codePostal }}</p>
                    <p class="margT">Latitude : {{ sortie.lieu.latitude }}</p>
                    <p class="margT">Longitude : {{ sortie.lieu.longitude }}</p>


<div>
    <h2>List de participant:</h2>
            {% for sub in sortie.users %}
                <li style="background-color: white; color: #0d0d0d"><a href="{{ path('profile_show', {id: sub.id}) }}">{{ sub.prenom }}</a> </li>
            {% endfor %}
</div>



    {% if app.user == sortie.user %}
            <a href="{{ path('sortie_edit', {'id': sortie.id}) }}" class="save-button">Modifier</a>
        {% if sortie.etat.libelle == "Créée" %}
            <a href="{{ path('sortie_publier', {'id': sortie.id}) }}" class="btn">Publier</a>
        {% endif %}
    {% endif %}

    {% if sortie.user == app.user and not sortie.etat.libelle == "Annulée" %}
        <a href="{{ path('sortie_cancel', {'id': sortie.id}) }}" class="btn btn-danger">Annuler la sortie</a>
    {% endif %}
                <div>
                    {% for label, messages in app.session.flashbag.all() %}
                        {% for message in messages %}
                            <div class="alert alert-{{ label }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                </div>


            </fieldset>
        </div>
    </div>
{% endblock %}

templates/sortie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}


{% block header %}
    <link rel="stylesheet" href="{{ asset('assets/css/navBis.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/containerPrinc.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/styleNewSorties.css') }}">
{% endblock %}

{% block body %}

    <div class="back">
<div class="containerPrinc">
    <div class="flexerMID ez form">
        <fieldset class="fieldset1 flexerMID fieldset3">
    {{ include('sortie/_form.html.twig', {'button_label': 'Update'}) }}
        </fieldset> </div>
</div>

    </div>



{% endblock %}

templates/sortie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SortieController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <h1>Hello {{ controller_name }}! ✅</h1>
        <nav>
            <ul>
                <li><a href="{{ path('villes') }}">Villes</a></li>
                <li><a href="{{ path('campus') }}">Campus</a></li>
                <li><a href="{{ path('accueil') }}">Accueil</a></li>
                <li><a href="{{ path('mon_profil') }}">Mon profil</a></li>
                <li><a href="{{ path('deconnexion') }}">Se déconnecter</a></li>
            </ul>
        </nav>
    </div>


{% endblock %}

templates/sortie/list.html.twig
{% extends 'base.html.twig' %}


{% block header %}
    <link rel="stylesheet" href="{{ asset('assets/css/styleList.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/containerPrinc.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/normalize.css') }}">
{% endblock %}

{% block title %}
    {{ parent() }} | Liste des sorties
{% endblock %}

{% block body %}

    <div class="containerPrinc">
        <div class="form-container">

            {{ form_start(filtre) }}
            <div class="form1">
                <div id="title_filtre"><p>Recherche Personnalisée</p></div>
                <div class="form1-filtres">
                    <div class="dateCampus">
                        <div class="containerCampus">
                            {{ form_label(filtre.campus) }}
                            {{ form_widget(filtre.campus) }}
                        </div>
                        <div class="containerDate">
                            {{ form_label(filtre.nom) }}
                            {{ form_widget(filtre.nom) }}

                            {# {{ form_label(filtre.dateSortie) }} #}
                            {{ form_row(filtre.dateSortie) }}

                            {{ form_label(filtre.dateCloture) }}
                            {{ form_widget(filtre.dateCloture) }}
                        </div>
                    </div>
                    <div class="containerFiltre">
                        <div class="checkboxFiltre">
                            <div class="margR">
                                {{ form_widget(filtre.sortieOrganisateur) }}
                            </div>
                            {{ form_label(filtre.sortieOrganisateur) }}
                        </div>
                        <div class="checkboxFiltre">
                            <div class="margR">
                                {{ form_widget(filtre.sortieInscrit) }}
                            </div>
                            {{ form_label(filtre.sortieInscrit) }}
                        </div>
                        <div class="checkboxFiltre">
                            <div class="margR">
                                {{ form_widget(filtre.sortiePasInscrit) }}
                            </div>
                            {{ form_label(filtre.sortiePasInscrit) }}
                        </div>
                        <div class="checkboxFiltre">
                            <div class="margR">
                                {{ form_widget(filtre.sortiePasses) }}
                            </div>
                            {{ form_label(filtre.sortiePasses) }}
                        </div>
                    </div>
                </div>
                <button>Rechercher</button>
            </div>
            {{ form_end(filtre) }}

            <div class="liste_sortir">
                <div class="titre_list">
                    <h1>Liste des sorties</h1>
                </div>

                <div>
                    {% for label, messages in app.session.flashbag.all() %}
                        {% for message in messages %}
                            <div class="alert alert-{{ label }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                </div>
                <div class="table-responsive">
                    <table id="table_sortir" class="table table-striped table-hover table-gradient table-wrapper">
                        <thead>
                        <tr>
                            <th scope="col" data-sort="nom">Nom de la sortie</th>
                            <th scope="col" data-sort="date">Date de la sortie</th>
                            <th scope="col" data-sort="cloture">Clôture des inscriptions</th>
                            <th scope="col" data-sort="inscris_numero">Inscrits/places totales</th>
                            <th scope="col" data-sort="etat">Etat</th>
                            <th scope="col" data-sort="inscrit">Inscrit</th>
                            <th scope="col" data-sort="organisateur">Organisateur</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for sortie in sortieFiltre %}
                            <tr data-index="{{ loop.index }}">
                                <th scope="row"><a
                                            href="{{ path('sortie_details', {'id': sortie.id }) }}">{{ sortie.nom|capitalize }}</a>
                                </th>
                                <td>{{ sortie.dateHeureDebut|date('d/m/Y h:i') }}</td>
                                <td>{{ sortie.dateLimiteInscription|date('d/m/y H:i') }}</td>
                                <td>{{ sortie.users|length }}/{{ sortie.nbInscriptionMax }}</td>
                                <td>{{ sortie.etat.libelle }}</td>
                                <td>
                                    {% if app.user in sortie.users %}
                                        <div class="fond_cross">
                                            <p class="cross">X</p>
                                        </div>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{{ path('profile_show', {'id': sortie.user.id}) }}">{{ sortie.user.nom }}</a>
                                </td>

                                <td>
                                    <div class="button_action_list">
                                        {# TODO penser à mettre les liens dans les href #}
                                        {% if not (sortie.etat.libelle == '') %}
                                            <a href="{{ path('sortie_details', {'id': sortie.id }) }}">
                                                <button class="button_afficher">Afficher</button>
                                            </a>
                                        {% endif %}
                                        {% if (sortie.etat.libelle == 'Ouverte') and  not (app.user in sortie.users) %}
                                            <a href="{{ path('sortie_inscription', {'id': sortie.id}) }}">
                                                <button class="button_inscrire">S'inscrire</button>
                                            </a>
                                        {% endif %}
                                        {% if (app.user in sortie.users) and not (app.user == sortie.user) %}
                                            <a href="{{ path('sortie_desinscription', {'id': sortie.id}) }}">
                                                <button class="button_desister">Se
                                                    désister
                                                </button>
                                            </a>
                                        {% endif %}
                                        {% if app.user == sortie.user %}
                                            {% if sortie.etat.libelle == 'Créée' %}
                                                <a href="{{ path('sortie_edit', {'id': sortie.id}) }}">
                                                    <button class="button_modifier">Modifier</button>
                                                </a>
                                                <a href="{{ path('sortie_publier', {'id': sortie.id}) }}">
                                                    <button class="button_publier">Publier</button>
                                                </a>
                                            {% endif %}
                                            {% if ( sortie.etat.libelle == 'Ouverte') or (sortie.etat.libelle == 'Clôturée') %}
                                                <a href="{{ path('sortie_cancel', {'id': sortie.id}) }}">
                                                    <button class="button_annuler">Annuler</button>
                                                </a>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>


                </div>
                <div class="addBouton">
                    <a href="{{ path('sortie_new') }}">
                        <button>Créer une sortie</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        const tabla = document.getElementById('table_sortir');
        const cabeceras = tabla.querySelectorAll('thead th');
        const filas = Array.from(tabla.querySelectorAll('tbody tr'));

        cabeceras.forEach(cabecera => {
            cabecera.addEventListener('click', () => {
                const columna = cabecera.getAttribute('data-column');
                const orden = cabecera.classList.contains('asc') ? 'desc' : 'asc';

                // Remover clases de orden en todas las cabeceras
                cabeceras.forEach(c => c.classList.remove('asc', 'desc'));

                // Ordenar las filas
                filas.sort((a, b) => {
                    const valorA = a.querySelector(`td[data-column="${columna}"]`).textContent;
                    const valorB = b.querySelector(`td[data-column="${columna}"]`).textContent;

                    if (orden === 'asc') {
                        return valorA.localeCompare(valorB);
                    } else {
                        return valorB.localeCompare(valorA);
                    }
                });

                // Agregar las filas ordenadas de nuevo a la tabla
                filas.forEach(fila => tabla.querySelector('tbody').appendChild(fila));

                // Agregar clase de orden a la cabecera
                cabecera.classList.add(orden);
            });
        });

    </script>

{% endblock %}

templates/sortie/sortie.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }} | Détails de la sortie
{% endblock %}

{% block body %}

{% endblock %}